config/routes.rb
Rebankme::Application.routes.draw do

  devise_for :admin_users, skip: [:registrations]
  as :admin_user do
    get 'admin_users/edit' => 'devise/registrations#edit',
        :as => 'edit_admin_user_registration'
    put 'admin_users/:id' => 'devise/registrations#update',
        :as => 'admin_user_registration'
  end

  root 'static#home'

  get 'start', to: 'account_finder#start', as: :account_finder_start
  match 'account_finder',
        to: 'account_finder#next_type_question',
        as: :account_type_finder,
        via: [:get, :post]

  match 'users/:user_id/find_account',
        to: 'account_finder#find_account',
        as: :account_finder,
        via: [:get, :post]

  resources :users
  get 'users/:user_id/request_email',
      to: 'users#request_email',
      as: :request_user_email
  get 'users/:user_id/:account_type_id/help_me_open',
      to: 'users#help_me_open',
      as: :account_opening_assistance

  get 'admin', to: 'admin#home', as: :admin

  scope '/admin' do
    resources :banks, :branches, :bank_accounts,
              only: [:index, :new, :create, :edit, :update, :destroy]

    authenticated :admin_user do
      match '/job_queue' => DelayedJobWeb,
            :anchor => false,
            via: [:get, :post],
            as: :job_queue
      match '/vanity(/:action(/:id(.:format)))',
            controller: :vanity,
            via: [:get, :post],
            as: :vanity
    end
  end
end

app/models/branch.rb
# (c) 2014 Blue Ridge Foundation New York, author: Paul Barnes-Hoggett
# This code is licensed under MIT license (see LICENSE.txt for details)
# == Schema Information
#
# Table name: branches
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  address_id :integer
#  telephone  :string(255)
#  hours      :string(255)
#  bank_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  street     :string(255)
#  city       :string(255)
#  state      :string(255)
#  zipcode    :string(255)
#  latitude   :float
#  longitude  :float
#
class Branch < ActiveRecord::Base
  validates :name, :bank_id, :zipcode, presence: true
  belongs_to :bank
  geocoded_by :full_address
  # rubocop:disable all
  # rubocop disabled as it wants to change proc { to do
  after_validation :geocode, if: lambda{ |obj|
    # will geocode if any of these properties changed...
    p = [:street_changed?, :city_changed?, :state_changed?, :zipcode_changed?]
    p.each do |property|
      return true if obj.send(property)
    end
    false
  }
  # rubocop:enable all

  def full_name
    "#{bank.name} - #{name}"
  end

  def full_address
    fields = [:street, :city, :state, :zipcode]
    res = ''
    fields.each do |element|
      res += "#{self[element]}, " unless self[element].blank?
    end
    res.chomp(', ')
  end
end

app/controllers/branches_controller.rb
# (c) 2014 Blue Ridge Foundation New York, author: Paul Barnes-Hoggett
# This code is licensed under MIT license (see LICENSE.txt for details)
class BranchesController < EditableObjectController
  def initialize
    super
    @item_class = Branch
  end

  private

  def item_params
    params.require(:branch).permit(:name,
                                   :bank_id,
                                   :street,
                                   :city,
                                   :state,
                                   :zipcode,
                                   :telephone,
                                   :hours)
  end
end

app/views/branches/_branch.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% present branch do |presenter| %>
<li><%= presenter.name_tag %>
<%= presenter.edit_tag %>
<%= presenter.delete_tag %>
</li>
<% end %>

app/views/branches/_fields.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<%= render partial: 'layouts/error_messages', locals:{presenter:presenter} %>

<%= presenter.bank_field_tag(f) %>
<%= presenter.name_field_tag(f) %>
<%= presenter.telephone_field_tag(f) %>
<%= presenter.hours_field_tag(f) %>
<div>
<%= presenter.street_field_tag(f) %>
<%= presenter.city_field_tag(f) %>
<%= presenter.state_field_tag(f) %>
<%= presenter.zipcode_field_tag(f) %>
</div>

app/views/branches/edit.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% present @item do |presenter| %>
<% provide(:heading,  'Edit Branch') %>
<% provide(:page_title, 'Edit Branch') %>
<%= render partial: 'layouts/new_edit_item', locals:{presenter:presenter} %>
<% end %>

app/views/branches/index.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% provide(:heading,  'All Branches') %>
<% provide(:page_title, 'All Branches') %>
<%= link_to('New Branch', new_branch_path, class: 'btn btn-primary') %>
<ul class='editable-object-list'>
<%= render @items %>
</ul>

app/views/branches/new.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% present @item do |presenter| %>
<% provide(:heading,  'New Branch') %>
<% provide(:page_title, 'New Branch') %>
<%= render partial: 'layouts/new_edit_item', locals:{presenter:presenter} %>
<% end %>