config/routes.rb
Rebankme::Application.routes.draw do

  devise_for :admin_users, skip: [:registrations]
  as :admin_user do
    get 'admin_users/edit' => 'devise/registrations#edit',
        :as => 'edit_admin_user_registration'
    put 'admin_users/:id' => 'devise/registrations#update',
        :as => 'admin_user_registration'
  end

  root 'static#home'

  get 'start', to: 'account_finder#start', as: :account_finder_start
  match 'account_finder',
        to: 'account_finder#next_type_question',
        as: :account_type_finder,
        via: [:get, :post]

  match 'users/:user_id/find_account',
        to: 'account_finder#find_account',
        as: :account_finder,
        via: [:get, :post]

  resources :users
  get 'users/:user_id/request_email',
      to: 'users#request_email',
      as: :request_user_email
  get 'users/:user_id/:account_type_id/help_me_open',
      to: 'users#help_me_open',
      as: :account_opening_assistance

  get 'admin', to: 'admin#home', as: :admin

  scope '/admin' do
    resources :banks, :branches, :bank_accounts,
              only: [:index, :new, :create, :edit, :update, :destroy]

    authenticated :admin_user do
      match '/job_queue' => DelayedJobWeb,
            :anchor => false,
            via: [:get, :post],
            as: :job_queue
      match '/vanity(/:action(/:id(.:format)))',
            controller: :vanity,
            via: [:get, :post],
            as: :vanity
    end
  end
end

app/models/bank.rb
# (c) 2014 Blue Ridge Foundation New York, author: Paul Barnes-Hoggett
# This code is licensed under MIT license (see LICENSE.txt for details)
# == Schema Information
#
# Table name: banks
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#
class Bank < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/controllers/banks_controller.rb
# (c) 2014 Blue Ridge Foundation New York, author: Paul Barnes-Hoggett
# This code is licensed under MIT license (see LICENSE.txt for details)
class BanksController < EditableObjectController
  def initialize
    super
    @item_class = Bank
  end

  private

  def item_params
    params.require(:bank).permit(:name)
  end
end

app/views/banks/_bank.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% present bank do |presenter| %>
<li><%= presenter.name_tag %>
<%= presenter.edit_tag %>
<%= presenter.delete_tag %>
</li>
<% end %>

app/views/banks/_fields.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<%= render partial: 'layouts/error_messages', locals:{presenter:presenter} %>
<%= f.label :name %>
<%= f.text_field :name %>

app/views/banks/edit.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% present @item do |presenter| %>
<% provide(:heading,  'Edit Bank') %>
<% provide(:page_title, 'Edit Bank') %>
<%= render partial: 'layouts/new_edit_item', locals:{presenter:presenter} %>
<% end %>

app/views/banks/index.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% provide(:heading,  'All Banks') %>
<% provide(:page_title, 'All Banks') %>
<%= link_to('New Bank', new_bank_path, class: 'btn btn-primary') %>
<ul class='editable-object-list'>
<%= render @items %>
</ul>

app/views/banks/new.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% present @item do |presenter| %>
<% provide(:heading,  'New Bank') %>
<% provide(:page_title, 'New Bank') %>
<%= render partial: 'layouts/new_edit_item', locals:{presenter:presenter} %>
<% end %>