config/routes.rb
Rebankme::Application.routes.draw do

  devise_for :admin_users, skip: [:registrations]
  as :admin_user do
    get 'admin_users/edit' => 'devise/registrations#edit',
        :as => 'edit_admin_user_registration'
    put 'admin_users/:id' => 'devise/registrations#update',
        :as => 'admin_user_registration'
  end

  root 'static#home'

  get 'start', to: 'account_finder#start', as: :account_finder_start
  match 'account_finder',
        to: 'account_finder#next_type_question',
        as: :account_type_finder,
        via: [:get, :post]

  match 'users/:user_id/find_account',
        to: 'account_finder#find_account',
        as: :account_finder,
        via: [:get, :post]

  resources :users
  get 'users/:user_id/request_email',
      to: 'users#request_email',
      as: :request_user_email
  get 'users/:user_id/:account_type_id/help_me_open',
      to: 'users#help_me_open',
      as: :account_opening_assistance

  get 'admin', to: 'admin#home', as: :admin

  scope '/admin' do
    resources :banks, :branches, :bank_accounts,
              only: [:index, :new, :create, :edit, :update, :destroy]

    authenticated :admin_user do
      match '/job_queue' => DelayedJobWeb,
            :anchor => false,
            via: [:get, :post],
            as: :job_queue
      match '/vanity(/:action(/:id(.:format)))',
            controller: :vanity,
            via: [:get, :post],
            as: :vanity
    end
  end
end

app/models/bank_account.rb
# (c) 2014 Blue Ridge Foundation New York, author: Paul Barnes-Hoggett
# This code is licensed under MIT license (see LICENSE.txt for details)
# == Schema Information
#
# Table name: bank_accounts
#
#  id              :integer          not null, primary key
#  account_type_id :integer
#  branch_id       :integer
#  name            :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#
class BankAccount < ActiveRecord::Base
  validates :name, :account_type_id, :branch_id, presence: true
  belongs_to :branch
  belongs_to :account_type

  delegate :latitude, :longitude, to: :branch

  scope :ordered_by_branch_ids,
        ->(branch_ids) { order(branch_ordering_statement(branch_ids)) }
  scope :having_account_type,
        ->(account_type) { where(account_type_id: account_type.id) }
  scope :available_at_branches,
        ->(branch_ids) { where(branch_id: branch_ids) }

  def self.branch_ordering_statement(branch_ids)
    ret = 'CASE'
    branch_ids.each_with_index do |p, i|
      ret << " WHEN branch_id = '#{p}' THEN #{i}"
    end
    ret << ' END'
  end

  def self.accounts_near(user, account_type, limit = 6)
    branch_ids = Branch.near([user.latitude, user.longitude],
                             10,
                             order: 'distance').limit(limit).map(&:id)
    return [] if branch_ids.count == 0
    # rubocop:disable Style/LineLength
    # because although long, its a clear chain
    available_at_branches(branch_ids).having_account_type(account_type).ordered_by_branch_ids(branch_ids)
    # rubocop:enable Style/LineLength
  end
end

app/controllers/bank_accounts_controller.rb
# (c) 2014 Blue Ridge Foundation New York, author: Paul Barnes-Hoggett
# This code is licensed under MIT license (see LICENSE.txt for details)
class BankAccountsController < EditableObjectController
  def initialize
    super
    @item_class = BankAccount
  end

  private

  def item_params
    params.require(:bank_account).permit(:name, :branch_id, :account_type_id)
  end
end

app/views/bank_accounts/_bank_account.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% present bank_account do |presenter| %>
<li><%= presenter.name_tag %>
<%= presenter.edit_tag %>
<%= presenter.delete_tag %>
</li>
<% end %>

app/views/bank_accounts/_fields.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<%= render partial: 'layouts/error_messages', locals:{presenter:presenter} %>

<%= presenter.name_field_tag(f) %>
<%= presenter.branch_field_tag(f) %>
<%= presenter.account_type_field_tag(f) %>

app/views/bank_accounts/edit.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% present @item do |presenter| %>
<% provide(:heading,  'Edit Bank Account') %>
<% provide(:page_title, 'Edit Bank Account') %>
<%= render partial: 'layouts/new_edit_item', locals:{presenter:presenter} %>
<% end %>

app/views/bank_accounts/index.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% provide(:heading,  'All Bank Accounts') %>
<% provide(:page_title, 'All Bank Accounts') %>
<%= link_to('New Bank Account', new_bank_account_path, class: 'btn btn-primary') %>
<ul class='editable-object-list'>
<%= render @items %>
</ul>

app/views/bank_accounts/new.html.erb
<%
# (c) 2014 Blue Ridge Foundation New York
# authors: Paul Barnes-Hoggett, Dylan Butman
# This code is licensed under MIT license (see LICENSE.txt for details)
%>
<% present @item do |presenter| %>
<% provide(:heading,  'New Bank Account') %>
<% provide(:page_title, 'New Bank Account') %>
<%= render partial: 'layouts/new_edit_item', locals:{presenter:presenter} %>
<% end %>